all: 
		g++ -Wall -std=c++20 -o TestQuadraticProbing TestQuadraticProbing.cpp

BiMap: 
		g++ -Wall -std=c++20 -o TestBiMap TestBiMap.cpp
run: 
		./TestQuadraticProbing
clean: 
		rm -r -f TestQuadraticProbing